Still broken
git-svn-id: https://trollbot.svn.sourceforge.net/svnroot/trollbot/trunk@35 79ca4b1d-1696-da11-8a5f-000b6a37957f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="src/main.c"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE TCL_CFLAGS TCL_LDFLAGS PHP_CFLAGS PHP_LDADD PHP_PREFIX CPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE TCLSH TCL_DEFS TCL_LIBS TCL_CPPFLAGS WITH_TCL_TRUE WITH_TCL_FALSE PHP_CFLAGS PHP_LDADD PHP_PREFIX CPP EGREP LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -814,11 +814,11 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-tcl-inc=PATH         Path to tcl.h
-  --with-tcl-lib=PATH         Path to libtcl8.x.so
-  --with-tcl-cflags=CFLAGS    CFLAG override for Tcl
-  --with-tcl-ldflags=LDFLAGS  LDFLAGS override for Tcl
- --without-tcl                Compile without TCL support
+  --with-tclconfig=PATH   use tclConfig.sh from PATH
+                          (configure gets Tcl configuration from here)
+  --with-tcl=PATH         use Tcl from PATH
+  --with-tclsh=TCLSH      use TCLSH as the tclsh program
+                          (let configure find Tcl using this program)
   --with-php=PATH         use PHP from PATH
 
 Some influential environment variables:
@@ -2822,156 +2822,200 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-
-without_tcl=""
-with_tcl_inc=""
-with_tcl_lib=""
-with_tcl_cflags=""
-with_tcl_ldflags=""
-
-TCL_INC=""
-TCL_LIB=""
-
-TCL_CFLAGS=""
-TCL_LDFLAGS=""
-
-TCL_VERSION_MAJ=""
-TCL_VERSION_MIN=""
+# --- BEGIN CMU_TCL ---
 
 
-# Check whether --with-tcl-inc or --without-tcl-inc was given.
-if test "${with_tcl_inc+set}" = set; then
-  withval="$with_tcl_inc"
-  with_tcl_inc=$withval
+# Check whether --with-tclconfig or --without-tclconfig was given.
+if test "${with_tclconfig+set}" = set; then
+  withval="$with_tclconfig"
+  	TclLibBase=`echo ${withval} | sed s/tclConfig.sh\$//`
 fi;
 
-
-# Check whether --with-tcl-lib or --without-tcl-lib was given.
-if test "${with_tcl_lib+set}" = set; then
-  withval="$with_tcl_lib"
-  with_tcl_lib=$withval
+# Check whether --with-tcl or --without-tcl was given.
+if test "${with_tcl+set}" = set; then
+  withval="$with_tcl"
+  TclLibBase="${withval}/lib"
 fi;
 
-
-# Check whether --with-tcl-cflags or --without-tcl-cflags was given.
-if test "${with_tcl_cflags+set}" = set; then
-  withval="$with_tcl_cflags"
-  with_tcl_cflags=$withval
+# Check whether --with-tclsh or --without-tclsh was given.
+if test "${with_tclsh+set}" = set; then
+  withval="$with_tclsh"
+  TCLSH="${withval}"
 fi;
 
+if test "$TCLSH" = "no" -o "$with_tclconfig" = "no" ; then
+  { echo "$as_me:$LINENO: WARNING: Tcl disabled because tclsh or tclconfig specified as \"no\"" >&5
+echo "$as_me: WARNING: Tcl disabled because tclsh or tclconfig specified as \"no\"" >&2;}
+  with_tcl=no
+fi
 
-# Check whether --with-tcl-ldflags or --without-tcl-ldflags was given.
-if test "${with_tcl_ldflags+set}" = set; then
-  withval="$with_tcl_ldflags"
-  with_tcl_ldflags=$withval
-fi;
+if test "$with_tcl" != "no"; then
+  if test \! -z "$with_tclconfig" -a \! -d "$with_tclconfig" ; then
+    { { echo "$as_me:$LINENO: error: --with-tclconfig requires a directory argument." >&5
+echo "$as_me: error: --with-tclconfig requires a directory argument." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 
+  if test \! -z "$TCLSH" -a \! -x "$TCLSH" ; then
+    { { echo "$as_me:$LINENO: error: --with-tclsh must specify an executable file." >&5
+echo "$as_me: error: --with-tclsh must specify an executable file." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 
+  if test -z "$TclLibBase"; then # do we already know?
+    # No? Run tclsh and ask it where it lives.
 
-# Check whether --with-without_tcl or --without-without_tcl was given.
-if test "${with_without_tcl+set}" = set; then
-  withval="$with_without_tcl"
-  without_tcl=no
-fi;
+    # Do we know where a tclsh lives?
+    if test -z "$TCLSH"; then
+      # Try and find tclsh.  Any tclsh.
+      # If a new version of tcl comes out and unfortunately adds another
+      # filename, it should be safe to add it (to the front of the line --
+      # somef vendors have older, badly installed tclshs that we want to avoid
+      # if we can)
+      for ac_prog in tclsh8.4 tclsh8.3 tclsh8.2 tclsh8.1 tclsh8.0 tclsh
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_TCLSH+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $TCLSH in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_TCLSH="$TCLSH" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_TCLSH="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
 
-if test "x${without_tcl}" = "x" ; then
-        if test "x${with_tcl_inc}" = "x"; then
-        echo "${with_tcl_inc}"
-        echo "$as_me:$LINENO: checking for tcl.h in $with_tcl_inc" >&5
-echo $ECHO_N "checking for tcl.h in $with_tcl_inc... $ECHO_C" >&6
-        if test -r "${with_tcl_inc}/tcl.h" ; then
-            TCL_INC=${with_tcl_inc}
-            echo "$as_me:$LINENO: result: found" >&5
-echo "${ECHO_T}found" >&6
-        else
-            echo "$as_me:$LINENO: result: not found" >&5
-echo "${ECHO_T}not found" >&6
-        fi
+  ;;
+esac
+fi
+TCLSH=$ac_cv_path_TCLSH
+
+if test -n "$TCLSH"; then
+  echo "$as_me:$LINENO: result: $TCLSH" >&5
+echo "${ECHO_T}$TCLSH" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$TCLSH" && break
+done
+test -n "$TCLSH" || TCLSH=""unknown""
+
     fi
 
-    if test -r "${with_tcl_lib}" ; then
-        echo "$as_me:$LINENO: checking for tcl??.so or .dll" >&5
-echo $ECHO_N "checking for tcl??.so or .dll... $ECHO_C" >&6
-        if test -r "${with_tcl_lib}/libtcl??.so" ; then
-            TCL_LIB=${with_tcl_lib}
-            echo "$as_me:$LINENO: result: found" >&5
-echo "${ECHO_T}found" >&6
-        else
-                        if test -r "${with_tcl_lib}/libtcl??.dll" ; then
-                TCL_LIB=${with_tcl_lib}
-                echo "$as_me:$LINENO: result: found" >&5
-echo "${ECHO_T}found" >&6
-            else
-                echo "$as_me:$LINENO: result: not found" >&5
-echo "${ECHO_T}not found" >&6
-            fi
-        fi
+    # Do we know where to get a tclsh?
+    if test "${TCLSH}" != "unknown"; then
+      echo "$as_me:$LINENO: checking where Tcl says it lives" >&5
+echo $ECHO_N "checking where Tcl says it lives... $ECHO_C" >&6
+      TclLibBase=`echo puts \\\$tcl_library | ${TCLSH} | sed -e 's,^/*$,,'`
+      echo "$as_me:$LINENO: result: $TclLibBase" >&5
+echo "${ECHO_T}$TclLibBase" >&6
     fi
+  fi
 
+  if test -z "$TclLibBase" ; then
+    echo "$as_me:$LINENO: result: can't find tclsh" >&5
+echo "${ECHO_T}can't find tclsh" >&6
+    { echo "$as_me:$LINENO: WARNING: can't find Tcl installtion; use of Tcl disabled." >&5
+echo "$as_me: WARNING: can't find Tcl installtion; use of Tcl disabled." >&2;}
+    with_tcl=no
+  else
+    echo "$as_me:$LINENO: checking for tclConfig.sh" >&5
+echo $ECHO_N "checking for tclConfig.sh... $ECHO_C" >&6
+    # Check a list of places where the tclConfig.sh file might be.
+    for tcldir in "${TclLibBase}" \
+                  "${TclLibBase}/.." \
+		  "${TclLibBase}"`echo ${TCLSH} | sed s/sh//` ; do
+      if test -f "${tcldir}/tclConfig.sh"; then
+        TclLibBase="${tcldir}"
+        break
+      fi
+    done
 
-    if test "x${TCL_INC}" = "x" ; then
-        echo "$as_me:$LINENO: checking for tcl.h in /usr/include" >&5
-echo $ECHO_N "checking for tcl.h in /usr/include... $ECHO_C" >&6
-        if test -r "/usr/include/tcl.h" ; then
-            echo "$as_me:$LINENO: result: found" >&5
-echo "${ECHO_T}found" >&6
-            TCL_INC="/usr/include"
-        else
-            echo "$as_me:$LINENO: result: not found" >&5
-echo "${ECHO_T}not found" >&6
-            echo "$as_me:$LINENO: checking for tcl.h in /usr/local/include" >&5
-echo $ECHO_N "checking for tcl.h in /usr/local/include... $ECHO_C" >&6
-            if test -r "/usr/local/include/tcl.h" ; then
-                echo "$as_me:$LINENO: result: found" >&5
-echo "${ECHO_T}found" >&6
-                TCL_INC="/usr/local/include"
-            else
-                echo "$as_me:$LINENO: result: not found" >&5
-echo "${ECHO_T}not found" >&6
-            fi
-        fi
-    fi
-
-    if test "x${TCL_LIB}" = "x" ; then
-        if test -r "/usr/lib/libtcl??.so" ; then
-            TCL_LIB="/usr/lib"
-        fi
-
-                if test -r "/usr/lib/libtcl??.dll" ; then
-            TCL_LIB="/usr/lib"
-        fi
-
-        if test -r "/usr/local/lib/libtcl??.so" ; then
-            TCL_LIB="/usr/local/lib"
-        fi
-
-                if test -r "/usr/local/lib/libtcl??.dll" ; then
-            TCL_LIB="/usr/local/lib"
-        fi
-    fi
-
-        echo "$as_me:$LINENO: checking for the usability of tcl.h" >&5
-echo $ECHO_N "checking for the usability of tcl.h... $ECHO_C" >&6
-    if test "x${TCL_INC}" != "x" ; then
-        echo "$as_me:$LINENO: result: Yes" >&5
-echo "${ECHO_T}Yes" >&6
-        echo "$as_me:$LINENO: checking for the usability of libtcl??.so or libtcl??.dll" >&5
-echo $ECHO_N "checking for the usability of libtcl??.so or libtcl??.dll... $ECHO_C" >&6
-        if test "x${TCL_LIB}" != "x" ; then
-            echo "$as_me:$LINENO: result: Yes " >&5
-echo "${ECHO_T}Yes " >&6
-        else
-            echo "$as_me:$LINENO: result: No" >&5
-echo "${ECHO_T}No" >&6
-        fi
+    if test -z "${TclLibBase}" ; then
+      echo "$as_me:$LINENO: result: \"unknown\"" >&5
+echo "${ECHO_T}\"unknown\"" >&6
+      { echo "$as_me:$LINENO: WARNING: can't find Tcl configuration; use of Tcl disabled." >&5
+echo "$as_me: WARNING: can't find Tcl configuration; use of Tcl disabled." >&2;}
+      with_tcl=no
     else
-        echo "$as_me:$LINENO: result: Not found" >&5
-echo "${ECHO_T}Not found" >&6
+      echo "$as_me:$LINENO: result: ${TclLibBase}/" >&5
+echo "${ECHO_T}${TclLibBase}/" >&6
     fi
 
+    if test "${with_tcl}" != no ; then
+      echo "$as_me:$LINENO: checking Tcl configuration on what Tcl needs to compile" >&5
+echo $ECHO_N "checking Tcl configuration on what Tcl needs to compile... $ECHO_C" >&6
+      . ${TclLibBase}/tclConfig.sh
+      echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6
+                fi
+
+    if test "${with_tcl}" != no ; then
+                              echo "$as_me:$LINENO: checking where Tcl includes are" >&5
+echo $ECHO_N "checking where Tcl includes are... $ECHO_C" >&6
+      for tclinclude in "${TCL_PREFIX}/include/tcl${TCL_VERSION}" \
+                        "${TCL_PREFIX}/include/tcl" \
+                        "${TCL_PREFIX}/include" ; do
+        if test -r "${tclinclude}/tcl.h" ; then
+          TCL_CPPFLAGS="-I${tclinclude}"
+          break
+        fi
+      done
+      if test -z "${TCL_CPPFLAGS}" ; then
+        { echo "$as_me:$LINENO: WARNING: can't find Tcl includes; use of Tcl disabled." >&5
+echo "$as_me: WARNING: can't find Tcl includes; use of Tcl disabled." >&2;}
+        with_tcl=no
+      fi
+      echo "$as_me:$LINENO: result: ${TCL_CPPFLAGS}" >&5
+echo "${ECHO_T}${TCL_CPPFLAGS}" >&6
+    fi
+
+    # Finally, pick up the Tcl configuration if we haven't found an
+    # excuse not to.
+    if test "${with_tcl}" != no; then
+            TCL_LIBS="${TCL_LIB_SPEC} ${TCL_LIBS}"
+    fi
+  fi
 fi
 
 
+
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TCL 1
+_ACEOF
+
+
+# --- END CMU_TCL ---
+
+
+
+
+if test "x${TCL_LIBS}" != "x"; then
+  WITH_TCL_TRUE=
+  WITH_TCL_FALSE='#'
+else
+  WITH_TCL_TRUE='#'
+  WITH_TCL_FALSE=
+fi
 
 
 
@@ -3600,6 +3644,13 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${WITH_TCL_TRUE}" && test -z "${WITH_TCL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WITH_TCL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WITH_TCL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -4171,8 +4222,12 @@ s,@AMDEPBACKSLASH@,$AMDEPBACKSLASH,;t t
 s,@CCDEPMODE@,$CCDEPMODE,;t t
 s,@am__fastdepCC_TRUE@,$am__fastdepCC_TRUE,;t t
 s,@am__fastdepCC_FALSE@,$am__fastdepCC_FALSE,;t t
-s,@TCL_CFLAGS@,$TCL_CFLAGS,;t t
-s,@TCL_LDFLAGS@,$TCL_LDFLAGS,;t t
+s,@TCLSH@,$TCLSH,;t t
+s,@TCL_DEFS@,$TCL_DEFS,;t t
+s,@TCL_LIBS@,$TCL_LIBS,;t t
+s,@TCL_CPPFLAGS@,$TCL_CPPFLAGS,;t t
+s,@WITH_TCL_TRUE@,$WITH_TCL_TRUE,;t t
+s,@WITH_TCL_FALSE@,$WITH_TCL_FALSE,;t t
 s,@PHP_CFLAGS@,$PHP_CFLAGS,;t t
 s,@PHP_LDADD@,$PHP_LDADD,;t t
 s,@PHP_PREFIX@,$PHP_PREFIX,;t t
@@ -4896,17 +4951,4 @@ if test "$no_create" != yes; then
 fi
 
 
-echo "Trollbot is now configured with the following options"
-
-if test "x${WITH_TCL}" = "x"; then
-    echo "TCL Support: NO"
-else
-    echo "TCL Support: YES"
-fi
-
-if test "x${WITH_PHP}" = "x"; then
-    echo "PHP Support: NO"
-else
-    echo "PHP Support: YES"
-fi
 
