Added perl interpreter, perl lib soon to come, lots of code cleanup
git-svn-id: https://trollbot.svn.sourceforge.net/svnroot/trollbot/trunk@40 79ca4b1d-1696-da11-8a5f-000b6a37957f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="src/main.c"
-ac_subst_vars='VERSION SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE TCLSH TCL_DEFS TCL_LIBS TCL_CPPFLAGS WITH_TCL_TRUE WITH_TCL_FALSE PHP_CFLAGS PHP_LDADD PHP_PREFIX WITH_PHP_TRUE WITH_PHP_FALSE CPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='VERSION SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE TCLSH TCL_DEFS TCL_LIBS TCL_CPPFLAGS WITH_TCL_TRUE WITH_TCL_FALSE PHP_CFLAGS PHP_LDADD PHP_PREFIX WITH_PHP_TRUE WITH_PHP_FALSE PERL PERL_LDADD PERL_CFLAGS WITH_PERL_TRUE WITH_PERL_FALSE CPP EGREP LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3087,6 +3087,74 @@ else
 fi
 
 
+
+
+  echo "$as_me:$LINENO: checking For perl binary" >&5
+echo $ECHO_N "checking For perl binary... $ECHO_C" >&6
+  # Extract the first word of "perl", so it can be a program name with args.
+set dummy perl; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PERL+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PERL in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PERL="$PERL" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PERL="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+PERL=$ac_cv_path_PERL
+
+if test -n "$PERL"; then
+  echo "$as_me:$LINENO: result: $PERL" >&5
+echo "${ECHO_T}$PERL" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+  if test "x${PERL}" != "x"; then
+    PERL_LDADD="`${PERL} -MExtUtils::Embed -e ldopts`"
+    PERL_CFLAGS="`${PERL} -MExtUtils::Embed -e ccopts`"
+
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PERL 1
+_ACEOF
+
+  fi
+
+
+
+
+if test "x${PERL_LDADD}" != "x"; then
+  WITH_PERL_TRUE=
+  WITH_PERL_FALSE='#'
+else
+  WITH_PERL_TRUE='#'
+  WITH_PERL_FALSE=
+fi
+
+
 echo "$as_me:$LINENO: checking whether ${MAKE-make} sets \$(MAKE)" >&5
 echo $ECHO_N "checking whether ${MAKE-make} sets \$(MAKE)... $ECHO_C" >&6
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y,:./+-,___p_,'`
@@ -3652,6 +3720,13 @@ if test -z "${WITH_PHP_TRUE}" && test -z "${WITH_PHP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"WITH_PHP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"WITH_PHP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WITH_PERL_TRUE}" && test -z "${WITH_PERL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WITH_PERL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WITH_PERL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4237,6 +4312,11 @@ s,@PHP_LDADD@,$PHP_LDADD,;t t
 s,@PHP_PREFIX@,$PHP_PREFIX,;t t
 s,@WITH_PHP_TRUE@,$WITH_PHP_TRUE,;t t
 s,@WITH_PHP_FALSE@,$WITH_PHP_FALSE,;t t
+s,@PERL@,$PERL,;t t
+s,@PERL_LDADD@,$PERL_LDADD,;t t
+s,@PERL_CFLAGS@,$PERL_CFLAGS,;t t
+s,@WITH_PERL_TRUE@,$WITH_PERL_TRUE,;t t
+s,@WITH_PERL_FALSE@,$WITH_PERL_FALSE,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
